# pulled from https://github.com/pion/mediadevices/blob/master/.github/workflows/ci.yaml
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.19'
    name: Linux Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: |
          sudo apt-get update -qq \
          && sudo apt-get install --no-install-recommends -y \
            libopus-dev \
            libopusfile-dev \
            libva-dev \
            libvpx-dev \
            libx264-dev
      - name: Run Test Suite
        run: make lint test
  macos:
    strategy:
      matrix:
        runs-on: macos-latest
        go:
          - '1.19'
    runs-on: ${{ matrix.runs-on }}
    name: macOS Go ${{ matrix.go }} ${{ join(matrix.runs-on, ' ') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout Homebrew
        if: matrix.runs-on != 'macos-latest'
        uses: actions/checkout@v3
        with:
          repository: Homebrew/brew
          path: homebrew
      - name: Install dependencies
        run: |
          which brew
          brew install \
            pkg-config \
            opus \
            opusfile \
            libvpx \
            x264
      - name: Run Test Suite
        run: make lint test
